"""Structured multi-subject curriculum data for the Canopy learning studio.

The atlas is intentionally deterministic and dependency-free.  It gives the
UI one stable contract for every course: a six-step reasoning path, practice
missions, evidence terms, flashcards, sources, and a bounded roleplay.  The
visual layer lives in :mod:`src.interactive_labs` so curriculum content can be
tested without importing Plotly or Streamlit.
"""

from __future__ import annotations

import copy
from typing import Any, Literal, Mapping, TypedDict


AcademyId = Literal["stem", "human-worlds"]
LabKind = Literal["surface", "projectile", "dna", "carbon", "network", "sources", "narrative", "claims", "ethics"]


class Academy(TypedDict):
    id: AcademyId
    label: str
    short_label: str
    icon: str
    description: str


class Course(TypedDict):
    id: str
    academy: AcademyId
    subject: str
    title: str
    subtitle: str
    icon: str
    accent: str
    age_band: str
    lab_kind: LabKind
    big_question: str
    misconception: str
    transfer_prompt: str
    roleplay_prompt: str
    diagnostic_groups: list[list[str]]
    path: list[dict[str, Any]]
    practice: list[dict[str, Any]]
    flashcards: list[dict[str, str]]
    sources: list[dict[str, str]]


_ACADEMIES: tuple[Academy, ...] = (
    {
        "id": "stem",
        "label": "STEM Studio",
        "short_label": "STEM",
        "icon": "⌬",
        "description": "Model systems, manipulate variables, test predictions, and explain what the evidence means.",
    },
    {
        "id": "human-worlds",
        "label": "Human Worlds · Humanities & Society",
        "short_label": "Human Worlds",
        "icon": "◌",
        "description": "Interrogate sources, trace perspectives, interpret meaning, weigh values, and defend a claim.",
    },
)


def _node(
    node_id: str,
    short: str,
    label: str,
    icon: str,
    color: str,
    model: str,
    question: str,
    description: str,
    hint: str,
    test: str,
) -> dict[str, Any]:
    """Build one render-ready learning node with a progressive explanation."""

    return {
        "id": node_id,
        "short": short,
        "label": label,
        "icon": icon,
        "color": color,
        "mastery": 0.0,
        "equation": model,
        "question": question,
        "description": description,
        "hint": hint,
        "explain_steps": (
            ("Notice the structure", model, description),
            ("Name the evidence", question, hint),
            ("Stress-test the model", test, "Change one assumption and predict what evidence should move if the model is useful."),
        ),
    }


def _practice(
    item_id: str,
    title: str,
    model: str,
    question: str,
    answer: str,
    terms: tuple[str, ...],
    skill: str,
    transfer: str,
    explanation: str,
    difficulty: int,
) -> dict[str, Any]:
    return {
        "id": item_id,
        "title": title,
        "equation": model,
        "question": question,
        "answer": answer,
        "answer_type": "text",
        "accepted_answers": [answer],
        "required_terms": list(terms),
        "skill": skill,
        "transfer": transfer,
        "hint_ladder": [
            "Name the most important relationship before giving a conclusion.",
            "Point to one piece of evidence in the model or source.",
            "Explain what would change your mind or alter the prediction.",
        ],
        "difficulty": difficulty,
        "explanation": explanation,
    }


_COURSES: tuple[Course, ...] = (
    {
        "id": "math-patterns",
        "academy": "stem",
        "subject": "Mathematics",
        "title": "Functions in Motion",
        "subtitle": "See parameters reshape a nonlinear system",
        "icon": "∿",
        "accent": "#76f2c0",
        "age_band": "Grades 8–12",
        "lab_kind": "surface",
        "big_question": "How does changing one parameter reshape an entire family of functions?",
        "misconception": "Treating a graph as a picture to memorize instead of a relationship generated by inputs and parameters.",
        "transfer_prompt": "Use the same parameter reasoning to predict how a sound wave, population model, or terrain map would change.",
        "roleplay_prompt": "A classmate says, “A parameter only changes one point on the graph.” Coach them using the surface and a counterexample.",
        "diagnostic_groups": [["parameter", "coefficient", "amplitude"], ["input", "domain", "x", "y"], ["surface", "output", "z", "shape"], ["predict", "change", "transform"]],
        "path": [
            _node("math-observe", "Observe", "Read the surface", "◈", "mint", "z = A·sin(fx)·cos(fy)", "Where are the peaks, valleys, and zeros?", "Translate a 3D surface into statements about inputs and outputs.", "Rotate the plot and find a place where z is close to zero.", "Hold frequency still and double amplitude."),
            _node("math-slice", "Slice", "Inspect a cross-section", "⌁", "blue", "y = 0  ⇒  z = A·sin(fx)", "What 2D curve appears when one input is fixed?", "Use a cross-section to connect familiar curves to a multivariable surface.", "Fix y mentally, then trace z as x changes.", "Compare the y=0 and y=π/(2f) slices."),
            _node("math-vary", "Vary", "Change a parameter", "↕", "coral", "A ↑  ⇒  |z|max ↑", "Which feature changes with amplitude, and which stays fixed?", "Separate vertical scaling from horizontal frequency.", "Change one control at a time and name what does not move.", "Predict the plot before moving the slider."),
            _node("math-model", "Model", "Build a rule", "ƒ", "violet", "period = 2π/f", "How can the surface reveal the period without solving every point?", "Connect repeating geometry to a symbolic rule.", "Measure the distance between neighboring peaks.", "Test the rule at two different frequencies."),
            _node("math-test", "Test", "Check an invariant", "✓", "gold", "z/A = sin(fx)·cos(fy)", "What ratio stays comparable when amplitude changes?", "Use normalization to expose structure hidden by scale.", "Divide the output by the amplitude before comparing surfaces.", "Try a negative amplitude and inspect orientation."),
            _node("math-transfer", "Transfer", "Design a terrain", "✺", "mint", "surface → model → prediction", "How would you tune the parameters to make low rolling hills or sharp ridges?", "Turn parameter knowledge into a design decision.", "Describe the desired geometry before choosing numbers.", "Defend your settings to another learner."),
        ],
        "practice": [
            _practice("math-frequency", "Frequency detective", "z = 2sin(3x)cos(3y)", "What changes if 3 becomes 6?", "The peaks become twice as frequent while amplitude stays 2.", ("frequency", "twice", "amplitude"), "Parameter sensitivity", "Where else does frequency control spacing?", "Frequency compresses the pattern horizontally; amplitude controls vertical scale.", 2),
            _practice("math-normalize", "Invariant hunt", "z/A = sin(fx)cos(fy)", "Why compare z/A across two surfaces?", "Normalizing removes amplitude so the underlying shape can be compared.", ("amplitude", "shape", "compare"), "Normalization", "How could normalization help compare populations of different sizes?", "A dimensionless ratio can reveal a common structure beneath different scales.", 3),
            _practice("math-design", "Terrain transfer", "A=?, f=?", "Choose parameters for tall, widely spaced hills and justify both choices.", "Use a large amplitude and a low frequency.", ("large", "amplitude", "low", "frequency"), "Model design", "Reverse the design for shallow, tightly spaced ripples.", "Large amplitude makes tall features; low frequency spreads them apart.", 4),
        ],
        "flashcards": [
            {"front": "What does amplitude control?", "back": "Vertical scale: the size of peaks and valleys."},
            {"front": "What does frequency control?", "back": "How rapidly a pattern repeats across the input axes."},
            {"front": "Why inspect a cross-section?", "back": "It turns a multivariable surface into a familiar one-variable curve."},
            {"front": "What is an invariant?", "back": "A relationship that remains stable while selected parameters change."},
        ],
        "sources": [
            {"label": "OpenStax · Algebra and Trigonometry", "url": "https://openstax.org/details/books/algebra-and-trigonometry-2e", "supports": "Functions, transformations, trigonometric models, and graphical reasoning."},
        ],
    },
    {
        "id": "physics-flight",
        "academy": "stem",
        "subject": "Physics",
        "title": "Motion in 3D",
        "subtitle": "Decompose a launch, predict a trajectory, test the model",
        "icon": "↗",
        "accent": "#8edbff",
        "age_band": "Grades 9–12",
        "lab_kind": "projectile",
        "big_question": "How do launch speed, angle, gravity, and crosswind jointly determine a trajectory?",
        "misconception": "Assuming horizontal and vertical motion compete with each other rather than being independently modeled components.",
        "transfer_prompt": "Design a safe launch that clears a barrier but lands inside a target zone, then defend the trade-off.",
        "roleplay_prompt": "A classmate says, “A steeper launch always travels farther.” Coach them with evidence from two trajectories.",
        "diagnostic_groups": [["horizontal", "vertical", "component"], ["gravity", "acceleration"], ["angle", "speed", "velocity"], ["range", "height", "time", "trajectory"]],
        "path": [
            _node("physics-observe", "Observe", "Read the flight", "◈", "blue", "r(t) = ⟨x(t), y(t), z(t)⟩", "Where is the object speeding up or slowing vertically?", "Treat the path as changing position over time in three dimensions.", "Hover over several points and compare time with height.", "Increase crosswind without changing launch speed."),
            _node("physics-split", "Split", "Resolve the velocity", "↗", "gold", "v₀ = ⟨v cosθ, w, v sinθ⟩", "Which component controls height, range, and sideways drift?", "Decompose one launch vector into independent directional components.", "Name each axis before calculating.", "Set wind to zero and predict the y-coordinate."),
            _node("physics-model", "Model", "Apply kinematics", "ƒ", "coral", "z(t)=v₀z·t−½gt²", "Why does the vertical coordinate curve while the horizontal one is nearly linear?", "Connect constant horizontal velocity with vertical gravitational acceleration.", "Look for the squared-time term.", "Change gravity and compare the curvature."),
            _node("physics-sim", "Simulate", "Run a parameter sweep", "⟳", "violet", "angle × speed × gravity", "Which control changes range most near the current launch?", "Use simulation to inspect sensitivity rather than guessing from one case.", "Move one slider at a time and record the landing point.", "Compare 30°, 45°, and 60° at the same speed."),
            _node("physics-validate", "Validate", "Check assumptions", "✓", "mint", "air resistance ≈ 0", "What real-world effect is absent from this model?", "Distinguish a useful idealization from reality.", "Ask whether the object, speed, and distance make drag negligible.", "Predict how drag would change range and symmetry."),
            _node("physics-design", "Design", "Engineer a launch", "✺", "gold", "constraint → model → test", "Can you clear 8 m while landing between 28 m and 34 m?", "Turn the model into an evidence-backed design decision.", "Use height and range together; one metric is not enough.", "Explain your chosen safety margin."),
        ],
        "practice": [
            _practice("physics-components", "Vector split", "v=20 m/s, θ=30°", "Which component changes when the launch angle rises?", "The vertical component increases while the horizontal component decreases at fixed speed.", ("vertical", "increase", "horizontal", "decrease"), "Vector decomposition", "How would a crosswind add a third component?", "At fixed speed, changing the angle redistributes velocity between axes.", 2),
            _practice("physics-gravity", "Gravity comparison", "Earth g=9.81; Moon g=1.62", "Predict the same launch on the Moon.", "It stays aloft longer, rises higher, and travels farther because gravity is weaker.", ("longer", "higher", "farther", "weaker"), "Model sensitivity", "Which assumptions become more important for a very long flight?", "Lower downward acceleration stretches both time aloft and horizontal range.", 3),
            _practice("physics-design", "Barrier challenge", "barrier=8 m; target=28–34 m", "Describe how you would tune and verify the launch.", "Adjust angle and speed, then check both maximum height and landing range.", ("angle", "speed", "height", "range"), "Constraint-based design", "Add a crosswind and revise the plan.", "A valid design satisfies every constraint, not merely maximum distance.", 4),
        ],
        "flashcards": [
            {"front": "Why split a launch vector?", "back": "Each axis follows a simpler rule; gravity acts vertically while horizontal motion continues."},
            {"front": "What creates the parabolic arc?", "back": "Constant horizontal velocity combined with constant downward acceleration."},
            {"front": "What does the ideal model omit?", "back": "Air resistance, spin, changing wind, terrain, and other real-world effects."},
            {"front": "What makes a simulation useful?", "back": "It exposes how predictions change when assumptions or parameters change."},
        ],
        "sources": [
            {"label": "OpenStax · Projectile Motion", "url": "https://openstax.org/books/physics/pages/5-3-projectile-motion", "supports": "Vector components, two-dimensional kinematics, trajectory, range, and model assumptions."},
        ],
    },
    {
        "id": "biology-code",
        "academy": "stem",
        "subject": "Biology",
        "title": "DNA → Protein",
        "subtitle": "Trace information through structure, mutation, and expression",
        "icon": "🧬",
        "accent": "#a998ff",
        "age_band": "Grades 8–12",
        "lab_kind": "dna",
        "big_question": "How can a one-base change travel from DNA structure to a different protein outcome?",
        "misconception": "Treating DNA as a static blueprint where every mutation necessarily changes the final protein.",
        "transfer_prompt": "Compare a silent, missense, and nonsense mutation and predict which layer of the system reveals each difference.",
        "roleplay_prompt": "A classmate says, “One changed base always ruins the organism.” Coach them through codons, redundancy, and evidence.",
        "diagnostic_groups": [["dna", "base", "sequence"], ["rna", "transcription"], ["protein", "translation", "amino"], ["mutation", "codon", "effect"]],
        "path": [
            _node("bio-structure", "Structure", "Read the double helix", "⌬", "violet", "A↔T   C↔G", "What stays paired as the helix twists?", "Connect 3D structure to complementary base pairing.", "Follow one rung and name both bases.", "Change the twist while preserving pairing."),
            _node("bio-copy", "Copy", "Model replication", "⎘", "blue", "DNA → DNA", "How can each strand guide a new partner?", "Use complementarity to explain semiconservative copying.", "Treat each original strand as a template.", "Predict the complement of a short sequence."),
            _node("bio-transcribe", "Transcribe", "Make an RNA message", "→", "mint", "DNA → RNA", "Which strand and pairing rules determine the RNA sequence?", "Translate stored information into a portable message.", "Remember that RNA uses U instead of T.", "Transcribe a sequence containing A, C, and T."),
            _node("bio-translate", "Translate", "Read codons", "⋮", "gold", "RNA → protein", "Why are three RNA bases read together?", "Connect codons to amino-acid sequence.", "Chunk the message into groups of three from the start position.", "Shift the reading frame by one base."),
            _node("bio-mutate", "Mutate", "Trace a variant", "✦", "coral", "base change → codon? → protein?", "When does a changed base alter the amino acid?", "Follow effects across layers rather than assuming damage.", "Compare the original and changed codons first.", "Move the mutation to a different codon position."),
            _node("bio-explain", "Explain", "Defend a mechanism", "✺", "violet", "structure → information → function", "What evidence would show that a variant changes protein function?", "Build a causal explanation with an uncertainty boundary.", "Separate sequence evidence from protein-function evidence.", "Explain a silent mutation to a younger learner."),
        ],
        "practice": [
            _practice("bio-complement", "Complement builder", "DNA: A C T G", "Write the complementary strand and explain the rule.", "T G A C, using A–T and C–G pairing.", ("t", "g", "a", "c", "pair"), "Complementary pairing", "How does RNA pairing differ?", "Each base has a specific partner, making templated copying possible.", 1),
            _practice("bio-central", "Information flow", "DNA → RNA → protein", "Explain why changing DNA may or may not change a protein.", "The change must alter an RNA codon in a way that changes translation or expression.", ("rna", "codon", "protein", "may"), "Central dogma reasoning", "What evidence belongs at each arrow?", "Information flows through multiple transformations, and redundancy can absorb some changes.", 3),
            _practice("bio-mutation", "Mutation detective", "GAA → GAG", "Both codons encode the same amino acid. What kind of outcome is this?", "A silent mutation at the protein-sequence level.", ("silent", "same", "amino"), "Variant interpretation", "Could a silent variant still affect expression?", "A base can change without changing the encoded amino acid, though other effects remain possible.", 4),
        ],
        "flashcards": [
            {"front": "What pairs with adenine in DNA?", "back": "Thymine; in RNA, adenine pairs with uracil."},
            {"front": "What is transcription?", "back": "Using DNA as a template to build an RNA message."},
            {"front": "What is translation?", "back": "Reading RNA codons to assemble an amino-acid chain."},
            {"front": "Why can a mutation be silent?", "back": "Different codons can specify the same amino acid."},
        ],
        "sources": [
            {"label": "NHGRI · Central Dogma", "url": "https://www.genome.gov/genetics-glossary/Central-Dogma", "supports": "The directional flow of genetic information from DNA to RNA to protein."},
        ],
    },
    {
        "id": "earth-carbon",
        "academy": "stem",
        "subject": "Earth & Climate Science",
        "title": "The Living Carbon Cycle",
        "subtitle": "Trace reservoirs, fluxes, feedbacks, and intervention",
        "icon": "◎",
        "accent": "#ffd66e",
        "age_band": "Grades 6–12",
        "lab_kind": "carbon",
        "big_question": "When one carbon flux changes, which reservoirs respond—and on what timescale?",
        "misconception": "Thinking carbon is simply created or destroyed rather than transferred among reservoirs at very different rates.",
        "transfer_prompt": "Design a portfolio that reduces atmospheric accumulation while acknowledging limits, delays, and trade-offs.",
        "roleplay_prompt": "A classmate says, “Planting trees instantly cancels fossil-fuel emissions.” Coach them using reservoir size, flux, and timescale.",
        "diagnostic_groups": [["reservoir", "atmosphere", "ocean", "soil"], ["flux", "flow", "transfer"], ["source", "sink"], ["time", "fast", "slow", "feedback"]],
        "path": [
            _node("carbon-map", "Map", "Name the reservoirs", "◉", "gold", "atmosphere ↔ land ↔ ocean ↔ rock", "Where can carbon be stored?", "Distinguish a reservoir from a process moving carbon.", "Name the boxes before following the arrows.", "Add fossil fuels and deep ocean to the map."),
            _node("carbon-trace", "Trace", "Follow one atom", "→", "mint", "reservoir → flux → reservoir", "Which process moves carbon along each arrow?", "Build a causal path through photosynthesis, respiration, combustion, and exchange.", "Use a verb for every arrow.", "Trace an atom from fuel to ocean sediment."),
            _node("carbon-quant", "Quantify", "Compare the fluxes", "Σ", "blue", "net = sources − sinks", "Why can large opposing flows still yield a smaller accumulation?", "Reason about net change rather than one arrow in isolation.", "Compare the total entering and leaving the atmosphere.", "Increase emissions while holding sinks constant."),
            _node("carbon-time", "Time", "Separate fast and slow", "⌛", "violet", "days ↔ millions of years", "Why can a balanced geological cycle still be disrupted quickly?", "Connect rates and timescales to system response.", "Ask how long each reservoir keeps carbon.", "Contrast seasonal plant uptake with rock weathering."),
            _node("carbon-feedback", "Feedback", "Find reinforcing loops", "⟳", "coral", "warming → ocean release → warming", "Which loop amplifies a change and which process buffers it?", "Identify feedback direction without calling every correlation a cause.", "Follow the sign of each arrow around the loop.", "Reverse one arrow and test the loop."),
            _node("carbon-design", "Design", "Evaluate interventions", "✺", "gold", "impact × scale × time × confidence", "Which action changes a meaningful flux without moving the problem elsewhere?", "Use system evidence to compare interventions.", "State the reservoir, flux, timescale, and uncertainty.", "Defend a mixed strategy instead of one magic solution."),
        ],
        "practice": [
            _practice("carbon-source-sink", "Source or sink?", "forest ↔ atmosphere", "How can the same forest be a sink one year and a source another?", "Uptake and release are opposing fluxes; the larger one determines the net role.", ("uptake", "release", "net", "flux"), "Net-flow reasoning", "Apply the same idea to the ocean.", "Source and sink describe net behavior over a period, not a permanent identity.", 2),
            _practice("carbon-timescale", "Fast versus slow", "respiration vs weathering", "Why does timescale matter when comparing these processes?", "Respiration moves carbon quickly; weathering stores it slowly, so they cannot offset changes on the same schedule.", ("quick", "slow", "time", "offset"), "Timescale comparison", "Name another fast and slow pair.", "A process can be large but too slow to balance a rapid perturbation.", 3),
            _practice("carbon-policy", "Intervention portfolio", "emissions ↓ + sinks ↑", "Propose two actions and name one limitation of each.", "Reduce fossil emissions and protect or restore sinks, while accounting for scale, permanence, and delay.", ("emission", "sink", "scale", "limit"), "Systems intervention", "How would you monitor whether the plan works?", "A resilient portfolio changes inputs and strengthens sinks while exposing uncertainty.", 4),
        ],
        "flashcards": [
            {"front": "Reservoir or flux?", "back": "A reservoir stores carbon; a flux is a rate moving carbon between reservoirs."},
            {"front": "What is a carbon sink?", "back": "A reservoir or process that takes up more carbon than it releases over a stated period."},
            {"front": "Why use net flow?", "back": "Opposing large flows can nearly cancel; net flow determines accumulation."},
            {"front": "Why do timescales matter?", "back": "A slow process may not counter a rapid change when the response is needed."},
        ],
        "sources": [
            {"label": "NASA Earth Observatory · The Carbon Cycle", "url": "https://science.nasa.gov/earth/earth-observatory/the-carbon-cycle/", "supports": "Carbon reservoirs, slow and fast cycles, natural fluxes, and human perturbations."},
        ],
    },
    {
        "id": "cs-networks",
        "academy": "stem",
        "subject": "Computer Science",
        "title": "Algorithms as Paths",
        "subtitle": "See graph search unfold in space and time",
        "icon": "⌘",
        "accent": "#ff897a",
        "age_band": "Grades 7–12",
        "lab_kind": "network",
        "big_question": "How does a search strategy change the order, memory cost, and path it discovers?",
        "misconception": "Assuming breadth-first and depth-first search explore the same nodes in the same order because the graph is unchanged.",
        "transfer_prompt": "Choose a search strategy for a maze, a social network, and a dependency tree, then defend each choice.",
        "roleplay_prompt": "A classmate says, “DFS is always faster because it goes straight ahead.” Coach them with a counterexample.",
        "diagnostic_groups": [["node", "edge", "graph"], ["queue", "stack", "frontier"], ["breadth", "depth", "bfs", "dfs"], ["order", "path", "memory", "shortest"]],
        "path": [
            _node("cs-model", "Model", "Represent the network", "⌬", "coral", "G = (V, E)", "What belongs in the node set and edge set?", "Translate a real system into entities and relationships.", "Say what each node and edge means before searching.", "Model a transit map and a prerequisite map."),
            _node("cs-frontier", "Frontier", "Track what is next", "…", "gold", "frontier = candidates", "Why does the frontier data structure matter?", "Connect queue or stack behavior to search order.", "Write the frontier after each visit.", "Swap a queue for a stack."),
            _node("cs-bfs", "BFS", "Expand by layers", "◎", "blue", "queue: first in, first out", "Why can BFS find a shortest unweighted path?", "See equal-distance layers before moving deeper.", "Color nodes by distance from the start.", "Add one shortcut edge and predict the change."),
            _node("cs-dfs", "DFS", "Explore one branch", "↧", "violet", "stack: last in, first out", "When does going deep help, and when can it waste work?", "Connect branch order to recursion and backtracking.", "Follow the newest frontier node first.", "Move the goal to a shallow neighboring branch."),
            _node("cs-debug", "Debug", "Detect repeats", "✓", "mint", "visited prevents cycles", "What happens if a cyclic graph has no visited set?", "Use invariants to prevent repeated or infinite work.", "Mark a node when it enters or leaves the frontier—then be consistent.", "Remove the visited rule in a triangle."),
            _node("cs-choose", "Choose", "Match algorithm to task", "✺", "coral", "goal + constraints → strategy", "Which matters here: shortest path, memory, or quickly finding any solution?", "Choose an algorithm from requirements rather than habit.", "Name the graph type and success criterion.", "Defend a hybrid or bidirectional search."),
        ],
        "practice": [
            _practice("cs-frontier", "Frontier trace", "A→{B,C}; B→D; C→E", "Give the BFS visit order from A.", "A, B, C, D, E using a queue.", ("a", "b", "c", "d", "e", "queue"), "Search tracing", "How could neighbor ordering alter DFS?", "BFS visits all nodes one edge away before nodes two edges away.", 2),
            _practice("cs-cycle", "Cycle guard", "A→B→C→A", "Why is a visited set necessary?", "It prevents revisiting nodes forever and avoids duplicate work.", ("revisit", "forever", "duplicate", "visited"), "Graph invariants", "When should a node be marked visited?", "Cyclic graphs require explicit memory of explored states.", 3),
            _practice("cs-strategy", "Strategy choice", "shortest route in an unweighted maze", "Choose BFS or DFS and justify the choice.", "Choose BFS because it explores by distance and finds a shortest unweighted path.", ("bfs", "distance", "shortest"), "Algorithm selection", "When might DFS use less memory?", "The success criterion and graph properties determine the right search strategy.", 4),
        ],
        "flashcards": [
            {"front": "What does BFS use?", "back": "A queue, producing layer-by-layer exploration."},
            {"front": "What does DFS use?", "back": "A stack or recursion, producing branch-first exploration."},
            {"front": "Why track visited nodes?", "back": "To prevent cycles and repeated work."},
            {"front": "When is BFS shortest?", "back": "For path length measured in edges on an unweighted graph."},
        ],
        "sources": [
            {"label": "Canopy local lesson · Graph Search", "url": "https://en.wikipedia.org/wiki/Graph_traversal", "supports": "Graph representation, breadth-first search, depth-first search, and visited-state reasoning."},
        ],
    },
    {
        "id": "history-sources",
        "academy": "human-worlds",
        "subject": "History",
        "title": "History as Evidence",
        "subtitle": "Triangulate sources, context, perspective, and causation",
        "icon": "⌛",
        "accent": "#ffd66e",
        "age_band": "Grades 6–12",
        "lab_kind": "sources",
        "big_question": "Which sources best explain how the U.S. women’s suffrage movement produced political change?",
        "misconception": "Treating a source as neutral proof instead of evidence created by a person, for an audience, in a context.",
        "transfer_prompt": "Build a two-source argument that includes one tension or limitation rather than hiding disagreement.",
        "roleplay_prompt": "A classmate says, “The closest source to the event is automatically the most trustworthy.” Coach them through proximity, purpose, and corroboration.",
        "diagnostic_groups": [["source", "evidence", "document"], ["context", "audience", "purpose"], ["perspective", "bias", "stance"], ["corroborate", "compare", "limit", "cause"]],
        "path": [
            _node("history-observe", "Observe", "Notice before judging", "◈", "gold", "detail → question", "What do you notice before interpreting the source?", "Separate visible or textual details from conclusions.", "List concrete features without explaining them yet.", "Revisit the source after learning its date."),
            _node("history-context", "Context", "Place it in time", "⌛", "blue", "creator + audience + moment", "What was happening when and where this was created?", "Connect a source to conditions that shaped it.", "Ask who could act, speak, publish, or vote at the time.", "Shift the date by twenty years and reconsider meaning."),
            _node("history-perspective", "Perspective", "Map the viewpoint", "◐", "coral", "position ≠ automatic falsehood", "Whose interests and assumptions shape this account?", "Analyze perspective without reducing evidence to a bias label.", "Name what the creator could know and what they might want.", "Compare an organizer, opponent, and observer."),
            _node("history-corroborate", "Corroborate", "Build a source constellation", "⌬", "violet", "agreement + tension + silence", "Where do independent sources converge or diverge?", "Use multiple sources to refine rather than merely repeat a conclusion.", "Look for one agreement and one productive tension.", "Add quantitative evidence to a personal account."),
            _node("history-cause", "Cause", "Trace change over time", "→", "mint", "conditions + actions + contingencies", "Which factors made change possible, and which triggered it?", "Distinguish long-term conditions from short-term catalysts.", "Avoid a single-cause story; rank mechanisms with evidence.", "Remove one event and test whether the explanation survives."),
            _node("history-argue", "Argue", "Defend a historical claim", "✺", "gold", "claim + evidence + reasoning + limits", "What claim best fits the source constellation?", "Write an argument that exposes evidence quality and uncertainty.", "Include why the evidence supports the claim, not just a citation.", "Add a counter-source and revise the thesis."),
        ],
        "practice": [
            _practice("history-sourcing", "Source the document", "speech by movement organizer", "What three sourcing questions come before using it as evidence?", "Ask who created it, for which audience and purpose, and in what context.", ("who", "audience", "purpose", "context"), "Sourcing", "Apply the questions to a newspaper editorial.", "Creator, audience, purpose, and context shape what a source can reveal.", 2),
            _practice("history-corroboration", "Corroboration test", "petition + photograph + opposition pamphlet", "How can disagreement strengthen an analysis?", "It exposes competing perspectives and helps refine which claims each source can support.", ("perspective", "refine", "claim", "support"), "Corroboration", "What silence might remain across all three?", "Tension is evidence about the historical debate, not merely noise to discard.", 3),
            _practice("history-thesis", "Causal thesis", "1848–1920 source set", "Write a thesis with two mechanisms and one limitation.", "Organizing and public persuasion built pressure, while political opportunity converted pressure into law; the sources underrepresent marginalized voices.", ("organizing", "political", "law", "limit"), "Historical argument", "Which new source could address the limitation?", "A strong causal thesis combines mechanisms and acknowledges what its evidence cannot show.", 4),
        ],
        "flashcards": [
            {"front": "What is sourcing?", "back": "Investigating who created a source, when, for whom, and for what purpose."},
            {"front": "What is corroboration?", "back": "Comparing sources for convergence, disagreement, and silence."},
            {"front": "Does perspective make a source useless?", "back": "No. Perspective shapes what the source can reveal and how it should be interpreted."},
            {"front": "What distinguishes evidence from a quote?", "back": "Reasoning that explains why the source supports a particular claim."},
        ],
        "sources": [
            {"label": "Library of Congress · Primary Source Analysis", "url": "https://www.loc.gov/programs/teachers/getting-started-with-primary-sources/guides/", "supports": "Observe, reflect, question, and investigate primary sources using structured prompts."},
        ],
    },
    {
        "id": "literature-motifs",
        "academy": "human-worlds",
        "subject": "Literature",
        "title": "Narrative & Motif",
        "subtitle": "Trace how language, tension, and recurring images make meaning",
        "icon": "❧",
        "accent": "#a998ff",
        "age_band": "Grades 7–12",
        "lab_kind": "narrative",
        "big_question": "How do ambition, guilt, and disorder interact across Macbeth’s narrative arc?",
        "misconception": "Treating a theme as a one-word topic rather than a claim developed through patterns, choices, language, and consequences.",
        "transfer_prompt": "Compare the arc of one motif with a different play, novel, film, or lived narrative.",
        "roleplay_prompt": "A classmate says, “Ambition is the theme because ambition appears a lot.” Coach them from topic to interpretive claim.",
        "diagnostic_groups": [["pattern", "motif", "image"], ["language", "metaphor", "symbol"], ["character", "choice", "conflict"], ["theme", "claim", "meaning", "evidence"]],
        "path": [
            _node("lit-notice", "Notice", "Collect textual signals", "◈", "violet", "word/image/action → pattern", "Which repeated image or contradiction stands out?", "Begin with observable language before naming a theme.", "Track repetition, contrast, and shifts in diction.", "Compare the same image early and late in the play."),
            _node("lit-trace", "Trace", "Follow a motif", "⌁", "coral", "motif across acts", "Where does the motif intensify, invert, or disappear?", "Treat recurrence as change over time, not simple counting.", "Place each occurrence beside the character decision around it.", "Switch the lens from ambition to guilt."),
            _node("lit-connect", "Connect", "Link form and consequence", "↔", "blue", "language ↔ choice ↔ outcome", "How does the language change what a choice means?", "Connect literary technique to character action and audience effect.", "Use because, therefore, or however between evidence and claim.", "Remove the metaphor and test what interpretation is lost."),
            _node("lit-contrast", "Contrast", "Read a counter-pattern", "◐", "gold", "pattern A ≠ pattern B", "Which scene complicates your emerging interpretation?", "Use exceptions and ambiguity to deepen a claim.", "Find evidence that resists the simplest reading.", "Argue the opposite interpretation for one scene."),
            _node("lit-interpret", "Interpret", "Build a thematic claim", "✦", "mint", "pattern + change + consequence", "What does the play suggest—not merely mention—about power and self-knowledge?", "Turn observations into a contestable interpretive claim.", "Write a sentence another reader could reasonably challenge.", "Add one qualifier to avoid overclaiming."),
            _node("lit-rewrite", "Rewrite", "Transform the perspective", "✺", "violet", "same event, new lens", "How would the arc change from another character’s perspective?", "Use creative transformation as a test of interpretation.", "Preserve the original conflict while changing voice or form.", "Write a short scene from Banquo’s viewpoint."),
        ],
        "practice": [
            _practice("lit-topic-theme", "Topic to theme", "ambition", "Turn the topic into a thematic claim.", "Unchecked ambition can distort judgment until power becomes a source of fear rather than security.", ("ambition", "judgment", "power", "fear"), "Thematic reasoning", "Qualify the claim using one counterexample.", "A theme is an arguable statement about how a text develops an idea.", 2),
            _practice("lit-motif", "Motif trajectory", "blood imagery", "Explain how recurrence can change meaning across the play.", "Blood shifts from evidence of action to a symbol of guilt that cannot be mentally erased.", ("blood", "action", "guilt", "change"), "Motif analysis", "Trace a different sensory image.", "Motifs accumulate and transform meaning through their narrative context.", 3),
            _practice("lit-counter", "Counter-reading", "Macbeth as driven only by prophecy", "Give evidence that complicates this reading.", "His deliberation and choices show agency, so prophecy alone does not fully explain the outcome.", ("choice", "agency", "prophecy", "not"), "Interpretive complexity", "How would a deterministic reading respond?", "Strong interpretation tests itself against evidence that does not fit neatly.", 4),
        ],
        "flashcards": [
            {"front": "Topic versus theme?", "back": "A topic is a subject; a theme is an arguable claim the text develops about it."},
            {"front": "What is a motif?", "back": "A recurring element whose pattern and transformation contribute to meaning."},
            {"front": "What makes evidence literary?", "back": "Specific language, form, pattern, action, or structure interpreted in context."},
            {"front": "Why seek a counter-pattern?", "back": "It tests overconfident readings and can produce a more precise claim."},
        ],
        "sources": [
            {"label": "Project Gutenberg · Macbeth", "url": "https://www.gutenberg.org/ebooks/1533", "supports": "Public-domain primary text for tracing narrative events and recurring language."},
            {"label": "Poetry Foundation · Metaphor", "url": "https://www.poetryfoundation.org/education/glossary/metaphor", "supports": "A concise definition and examples of metaphor as a meaning-making comparison."},
        ],
    },
    {
        "id": "civics-information",
        "academy": "human-worlds",
        "subject": "Civics & Media Literacy",
        "title": "Civic Claims Lab",
        "subtitle": "Trace a public claim from source to evidence to judgment",
        "icon": "⚖",
        "accent": "#8edbff",
        "age_band": "Grades 7–12",
        "lab_kind": "claims",
        "big_question": "What makes a public claim verifiable, trustworthy, and useful for civic decision-making?",
        "misconception": "Equating confidence, popularity, or visual polish with evidence quality.",
        "transfer_prompt": "Create a verification plan for a statistic, quotation, or image before sharing it publicly.",
        "roleplay_prompt": "A classmate says, “Three accounts posted it, so it has been independently confirmed.” Coach them through source independence.",
        "diagnostic_groups": [["claim", "opinion", "verifiable"], ["source", "original", "independent"], ["evidence", "data", "context"], ["corroborate", "verify", "uncertain"]],
        "path": [
            _node("civic-classify", "Classify", "Claim or opinion?", "◈", "blue", "claim → checkable evidence?", "What part of the statement could be verified?", "Separate empirical claims from values and predictions.", "Rewrite the statement as one precise checkable proposition.", "Change a vague quantifier into a measurable one."),
            _node("civic-origin", "Origin", "Find the first source", "↶", "gold", "post → report → dataset", "Where did the information originate?", "Trace citations backward instead of counting repetitions.", "Open the earliest available source and inspect what it actually says.", "Compare a screenshot with the original context."),
            _node("civic-context", "Context", "Recover what is missing", "⌬", "violet", "who + when + method + denominator", "Which omitted detail could reverse the impression?", "Use surrounding context, methodology, and scale.", "For a statistic, ask compared with what and out of how many.", "Change the time window or denominator."),
            _node("civic-corroborate", "Corroborate", "Check independence", "↔", "mint", "independent evidence ≠ repeated citation", "Do the sources share the same underlying evidence?", "Distinguish independent confirmation from a citation cascade.", "Draw arrows back to the original evidence.", "Remove every source that depends on the same report."),
            _node("civic-calibrate", "Calibrate", "State confidence", "◐", "coral", "supported / uncertain / contradicted", "What conclusion is justified by the current evidence?", "Match confidence to evidence quality without forcing certainty.", "Name what is known, unknown, and needed next.", "Add one credible conflicting source."),
            _node("civic-publish", "Publish", "Communicate responsibly", "✺", "blue", "claim + source + context + uncertainty", "How can you share the finding without amplifying the misleading frame?", "Make evidence and limits visible to an audience.", "Lead with the corrected claim, not the sensational falsehood.", "Write a three-sentence verification note."),
        ],
        "practice": [
            _practice("civic-checkable", "Make it checkable", "“Everyone supports the policy.”", "Rewrite this as a verifiable claim.", "In a named poll, a stated percentage of a defined population supported the policy on a stated date.", ("poll", "percentage", "population", "date"), "Claim precision", "What sampling evidence would you need?", "Verifiability requires a defined measure, population, source, and time.", 2),
            _practice("civic-cascade", "Citation cascade", "five posts → one anonymous screenshot", "Why is this not five confirmations?", "All five depend on the same unverified origin, so the evidence is not independent.", ("same", "origin", "not", "independent"), "Source independence", "What would count as independent confirmation?", "Repetition can amplify one weak source without adding evidence.", 3),
            _practice("civic-verdict", "Calibrated verdict", "partial data + credible disagreement", "Write a responsible conclusion.", "The claim is not established; current evidence is mixed, and the missing method and original data should be obtained before sharing.", ("not", "mixed", "missing", "before"), "Uncertainty communication", "How would the verdict change with the original dataset?", "A responsible verdict exposes both evidence and unresolved uncertainty.", 4),
        ],
        "flashcards": [
            {"front": "What makes a claim checkable?", "back": "A precise statement linked to observable evidence, a population, and a timeframe."},
            {"front": "What is a citation cascade?", "back": "Many sources repeat one origin, creating apparent confirmation without independent evidence."},
            {"front": "Why inspect the denominator?", "back": "Percentages and rates can mislead when the comparison base is hidden."},
            {"front": "What is calibrated confidence?", "back": "Matching the strength of a conclusion to the quality and completeness of evidence."},
        ],
        "sources": [
            {"label": "UNESCO · Media and Information Literacy", "url": "https://www.unesco.org/mil4teachers/en/module4/unit5", "supports": "Fact-checking, claim analysis, inquiry, and documentation of verification steps."},
        ],
    },
    {
        "id": "ethics-decisions",
        "academy": "human-worlds",
        "subject": "Philosophy & Ethics",
        "title": "Ethical Trade-offs",
        "subtitle": "Map consequences, duties, stakeholders, and uncertainty",
        "icon": "◇",
        "accent": "#ff897a",
        "age_band": "Grades 9–12",
        "lab_kind": "ethics",
        "big_question": "How should a decision change when outcomes, rights, and uncertainty point in different directions?",
        "misconception": "Treating an ethical framework as a calculator that automatically produces a correct answer.",
        "transfer_prompt": "Apply the same framework comparison to a school policy, technology design, or environmental decision.",
        "roleplay_prompt": "A classmate says, “The option with the largest total benefit is automatically ethical.” Coach them through rights, distribution, and uncertainty.",
        "diagnostic_groups": [["stakeholder", "affected"], ["consequence", "outcome", "benefit", "harm"], ["right", "duty", "constraint"], ["uncertain", "risk", "trade-off", "justify"]],
        "path": [
            _node("ethics-stakeholders", "Stakeholders", "Map who is affected", "◎", "coral", "decision → people → impacts", "Whose interests are visible, and whose are easy to miss?", "Begin with affected agents before optimizing a result.", "Include indirect, future, and less powerful stakeholders.", "Add one stakeholder with limited voice."),
            _node("ethics-outcomes", "Outcomes", "Trace consequences", "→", "gold", "probability × magnitude × distribution", "What benefits and harms might follow, and for whom?", "Compare expected effects without hiding distribution.", "Separate likely outcomes from extreme possibilities.", "Change one probability and inspect the decision surface."),
            _node("ethics-rights", "Rights", "Identify constraints", "▣", "blue", "some actions may be impermissible", "Which duties or rights limit what may be done?", "Test whether outcomes alone capture the moral concern.", "Ask what must not be done to a person even for a benefit.", "Increase the rights weight in the landscape."),
            _node("ethics-perspective", "Perspective", "Compare frameworks", "◐", "violet", "consequence ↔ duty ↔ virtue", "Where do different ethical frameworks agree or conflict?", "Use frameworks as lenses that reveal different reasons.", "State what each lens notices and misses.", "Add care ethics or justice as another lens."),
            _node("ethics-uncertainty", "Uncertainty", "Reason under risk", "?", "mint", "known + unknown + moral risk", "How should uncertainty alter confidence or caution?", "Treat uncertainty as ethically relevant, not an excuse to stop reasoning.", "Name the uncertain fact and the consequence of being wrong.", "Test a low-probability, high-harm outcome."),
            _node("ethics-justify", "Justify", "Defend a revisable choice", "✺", "coral", "decision + reasons + objections + limits", "Which option can you justify to those who bear its costs?", "Build a transparent argument that can survive disagreement.", "Answer the strongest objection, not the easiest one.", "State what new evidence would change the decision."),
        ],
        "practice": [
            _practice("ethics-stakeholder", "Missing stakeholder", "school facial-recognition policy", "Name a stakeholder and impact that a convenience-only analysis might miss.", "Students falsely matched by the system may bear privacy, dignity, and disciplinary risks.", ("student", "privacy", "risk", "false"), "Stakeholder analysis", "Add the perspective of staff or families.", "Ethical analysis broadens who and what counts before comparing options.", 2),
            _practice("ethics-framework", "Framework contrast", "one option maximizes benefit but violates consent", "Explain the tension between outcomes and duties.", "Consequential reasoning favors the benefit, while a duty-based view treats valid consent as a constraint.", ("benefit", "duty", "consent", "constraint"), "Framework comparison", "Can a rule-consequentialist bridge the tension?", "Frameworks can disagree because they treat outcomes and constraints differently.", 3),
            _practice("ethics-uncertainty", "Decision under uncertainty", "small chance of severe irreversible harm", "What additional reasoning is needed beyond expected benefit?", "Consider the severity, reversibility, who bears the risk, rights constraints, and how uncertainty should change caution.", ("severity", "revers", "risk", "right", "uncertain"), "Moral uncertainty", "What evidence would reduce the uncertainty?", "Low-probability harms require attention to distribution, reversibility, and moral constraints.", 4),
        ],
        "flashcards": [
            {"front": "What is stakeholder analysis?", "back": "Identifying who is affected, how, and whose interests may be overlooked."},
            {"front": "Consequences versus duties?", "back": "One lens evaluates outcomes; another asks what actions or constraints are owed regardless of totals."},
            {"front": "Why does distribution matter?", "back": "The same total benefit can conceal that costs fall unfairly on particular people."},
            {"front": "What is a revisable justification?", "back": "A reasoned choice that states objections, limits, and evidence that would change it."},
        ],
        "sources": [
            {"label": "Stanford Encyclopedia of Philosophy · Moral Decision-Making Under Uncertainty", "url": "https://plato.stanford.edu/entries/moral-decision-uncertainty/", "supports": "Expected utility, moral constraints, risk, and uncertainty in ethical decision-making."},
            {"label": "Stanford Encyclopedia of Philosophy · Deontological Ethics", "url": "https://plato.stanford.edu/entries/ethics-deontological/", "supports": "Duties, rights, constraints, and contrasts with consequentialist theories."},
        ],
    },
)


def get_academies() -> list[Academy]:
    """Return independent academy records in display order."""

    return copy.deepcopy(list(_ACADEMIES))


def get_courses(academy: AcademyId | str | None = None) -> list[Course]:
    """Return independent courses, optionally filtered by academy."""

    if academy is None:
        return copy.deepcopy(list(_COURSES))
    normalized = str(academy).strip().lower()
    return copy.deepcopy([course for course in _COURSES if course["academy"] == normalized])


def get_course(course_id: str) -> Course:
    """Return one course by stable id."""

    for course in _COURSES:
        if course["id"] == course_id:
            return copy.deepcopy(course)
    raise KeyError(f"Unknown course: {course_id}")


def default_course_id(academy: AcademyId | str = "stem") -> str:
    """Return a compelling default course for an academy."""

    normalized = str(academy).strip().lower()
    return "physics-flight" if normalized == "stem" else "history-sources"


def course_nodes(course: Mapping[str, Any]) -> tuple[dict[str, Any], ...]:
    """Return a fresh tuple of path nodes for app rendering."""

    return tuple(copy.deepcopy(list(course.get("path", []))))


def course_practice(course: Mapping[str, Any]) -> tuple[dict[str, Any], ...]:
    """Return a fresh tuple of practice missions for app rendering."""

    return tuple(copy.deepcopy(list(course.get("practice", []))))


__all__ = [
    "Academy",
    "AcademyId",
    "Course",
    "LabKind",
    "course_nodes",
    "course_practice",
    "default_course_id",
    "get_academies",
    "get_course",
    "get_courses",
]
